### ISSUE TITLE
Inconsistent bower.json

### ISSUE THREAD

**Issue by alexkrauss** [dequelabs/ngA11y#18]
Currently, `bower.json` declares the javascript files under `src/` as main files, but also ignores the source folder.

As a consequence, when trying to use the package with bower, only the minified files under `dist/` get installed, but the (broken) references to the original source files get inserted as managed dependencies.

My suggestion would be not to ignore the `src/` folder, which includes the sources in the package. Alternatively, one could change the main files to be from `dist/`, but this would make it harder to use the non-minified sources for development.

**Comment by alexkrauss** [comment]
Moreover, `bower.json` references a file `nga11yfocus.css`, which does not seem to exist.

**Comment by dylanb** [comment]
I believe I have this fixed in version 0.0.8 - can you validate?

**Comment by alexkrauss** [comment]
`src/` is now properly visible, but the source file `nga11yfocus.js` is missing in the declaration.

**Comment by dylanb** [comment]
OK, now I have all the src files and the dist files in the main section so that both minified and unminified versions are available in the published repo

**Comment by alexkrauss** [comment]
Which commit is this? I see no changes to bower.json in the published 0.0.10 release... Did this get lost maybe?

**Comment by dylanb** [comment]
grrr...merge failure and trying to get something done too quickly...0.0.11 should now finally be fixed

**Comment by alexkrauss** [comment]
Just tried 0.0.11, but the results are still not what I was expecting (though I must say that my bower experience is still somewhat limited).

Some background:
- We are using 'grunt wiredep' to automatically wire dependencies into the main html file.
- The setup was generated by a vanilla yeoman setup for angular, so I would expect that it is fairly standard.
- The wiredep tool simply takes all the `main` files from bower and puts them into the `index.html` file.

So the result now is, that I get BOTH the original as well as the minified files into my index.html.
Looking at [the spec](https://github.com/bower/bower.json-spec), it seems to suggest that one should not declare minified files here.

Sorry for the confusion, but I am just trying to make 'convention over configuration' actually work :-)

**Comment by dylanb** [comment]
@alexkrauss thanks for that additional information. I somehow missed that bower is not supposed to have minified files in the main. I have updated it now.

**Comment by alexkrauss** [comment]
Works now with 0.0.12. Thanks.
