### ISSUE TITLE
"undefined" getting announced on form validation

### ISSUE THREAD

**Issue by dylanb** [dequelabs/ngA11y#19]
In the https://github.com/AnikG/smtt repository, when the table form fields validate as invalid (for example, the user enters just a ".") then there is an announcement of "undefined" being output to the live region.

**Comment by iandotkelly** [comment]
@dylanb @AnikG -  I don't have access to the application, but I can probably track that down easily enough without it.

**Comment by AnikG** [comment]
I added you as a collaborator.

-- Anik

**Comment by iandotkelly** [comment]
Closed by https://github.com/dequelabs/ngA11y/commit/b5d8b9386852bacfada64cd4a856551def27fb8b
