### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by kash-raman** [dequelabs/ngA11y#26]
Hi, 
I'm trying to use this module,  when used via npm install ngA11y version 1.0.0 is installed. And 'nga11yAnnounce' is not error-ing with "unknown provider" in controller 
 Error:  Unknown provider 

Whereas, if i clone and build using github, it works perfectly fine.   
https://www.npmjs.com/package/nga11y 

There seems to be a mismatch in version, can the latest be released?  
Also, can the master version number in package.json be incremented from npm registry.  currently , i see 0.0.0

**Comment by chandramuralis** [comment]
I don't think this particular package is released in npm library, it is only available through 'bower'. 
When you do npm search as below, you will see it is distributed by different user '[jacobharasimo](https://github.com/jacobharasimo/ngA11y)' and not '[dequelabs](https://github.com/dequelabs)'.

**Comment by marcysutton** [comment]
We are looking into this issue, thanks for bringing it to our attention.

**Comment by kash-raman** [comment]
@chandramuralis  The version released in npm(1.0.0) is old and not consistent with github latest.

**Comment by dylanb** [comment]
The owner of that npm repository (who forked our project) is being painful. We are thinking about a publishing this under ng-a11y and have reserved that npm package. Any objections to that name change here?

**Comment by chandramuralis** [comment]
I don't have any issue with that... but it might be little bit confusing for the users trying to install through npm or bower.

**Comment by marcysutton** [comment]
Give us a little time to sort it out; we'll be sure to let you all know the correct install process moving forward!

**Comment by dylanb** [comment]
@chandramuralis the bower module name is already ng-a11y

**Comment by chandramuralis** [comment]
True... It's perfect then.

**Comment by marcysutton** [comment]
We have published under the package name `ng-a11y`. You can now find releases here: https://www.npmjs.com/package/ng-a11y
